language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_install:
  - cd ../
  - composer create-project --keep-vcs unionofrad/framework framework 1.1.*@dev
  - mv li3_quality framework/app/libraries/li3_quality
  - cd framework

script: libraries/lithium/console/li3 test libraries/li3_quality/tests