language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_install:
  - cd ../
  - composer create-project --keep-vcs unionofrad/framework framework 1.1.*@dev
  - cd framework
  - mv ../li3_quality app/libraries/li3_quality
  - sed -i -e 's/?>/Libraries::add("li3_quality"); ?>/g' app/config/bootstrap/libraries.php

script: libraries/lithium/console/li3 test libraries/li3_quality/tests