language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_install:
  - cd ../
  - git clone git://github.com/UnionOfRAD/framework.git
  - mv li3_quality/ framework/app/libraries/li3_quality
  - cd framework
  - git submodule update --init --recursive
  - cd libraries/lithium && git pull --rebase origin master
  - cd ../../app/libraries/li3_quality

script: ../../../libraries/lithium/console/li3 test tests && ../../../libraries/lithium/console/li3 quality syntax --library=li3_quality
